BEGIN;
CREATE SCHEMA IF NOT EXISTS BL_CL;

DROP TABLE IF EXISTS BL_CL.MTA_LOADS;
CREATE TABLE IF NOT EXISTS BL_CL.MTA_LOADS
(
    PROCEDURE_NAME      VARCHAR(255)    NOT NULL,
    PROCEDURE_SCHEMA    VARCHAR(255)    NOT NULL,
    LAST_LOAD_DT        TIMESTAMP       NOT NULL,
    CONSTRAINT          UNQ_MTA_LOADS_PROCEDURE_NAME_PROCEDURE_SCHEMA UNIQUE (PROCEDURE_NAME, PROCEDURE_SCHEMA)
);

DROP PROCEDURE IF EXISTS BL_CL.SP_MTA_UPDATE_LOAD;
CREATE OR REPLACE PROCEDURE BL_CL.SP_MTA_UPDATE_LOAD(IN P_PROCEDURE_NAME VARCHAR, IN P_PROCEDURE_SCHEMA VARCHAR)
LANGUAGE PLPGSQL
AS $$
BEGIN
    INSERT INTO BL_CL.MTA_LOADS (PROCEDURE_NAME, PROCEDURE_SCHEMA, LAST_LOAD_DT)
    VALUES      (P_PROCEDURE_NAME,
                P_PROCEDURE_SCHEMA,
                CURRENT_TIMESTAMP)
    ON CONFLICT (PROCEDURE_NAME, PROCEDURE_SCHEMA) DO UPDATE
    SET         LAST_LOAD_DT = CURRENT_TIMESTAMP;
EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION 'ERROR UPDATING LOAD (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;
COMMIT;