BEGIN;
CREATE SCHEMA IF NOT EXISTS BL_CL;

DROP PROCEDURE IF EXISTS BL_CL.SP_CL_MASTER_PROCEDURE;
CREATE OR REPLACE PROCEDURE BL_CL.SP_CL_MASTER_PROCEDURE()
LANGUAGE PLPGSQL
AS $$
BEGIN    
    CALL BL_CL.SP_SA_ONLINE_LOAD_SRC_ONLINE_RETAIL_SALES();
    CALL BL_CL.SP_SA_OFFLINE_LOAD_SRC_OFFLINE_RETAIL_SALES();
    
    CALL BL_CL.SP_CL_LOAD_T_MAP_PRODUCT_CATEGORIES();
    CALL BL_CL.SP_CL_LOAD_T_MAP_PRODUCT_SUBCATEGORIES();
    CALL BL_CL.SP_CL_LOAD_T_MAP_PRODUCTS();
    CALL BL_CL.SP_CL_LOAD_T_MAP_PAYMENT_METHODS();
    CALL BL_CL.SP_CL_LOAD_T_MAP_CARD_TYPES();
    CALL BL_CL.SP_CL_LOAD_T_MAP_PAYMENT_DETAILS();
    
    CALL BL_CL.SP_3NF_LOAD_CE_CUSTOMERS_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_PRODUCT_CATEGORIES_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_PRODUCT_SUBCATEGORIES_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_PRODUCTS_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_REGIONS_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_COUNTRIES_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_CITIES_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_ADDRESSES_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_EMPLOYEES_SCD_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_PAYMENT_METHODS_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_CARD_TYPES_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_PAYMENT_DETAILS_DEFAULT();
    CALL BL_CL.SP_3NF_LOAD_CE_DEVICES_DEFAULT();
    
    CALL BL_CL.SP_DM_LOAD_DIM_CUSTOMERS_DEFAULT();
    CALL BL_CL.SP_DM_LOAD_DIM_PRODUCTS_DEFAULT();
    CALL BL_CL.SP_DM_LOAD_DIM_LOCATIONS_DEFAULT();
    CALL BL_CL.SP_DM_LOAD_DIM_EMPLOYEES_SCD_DEFAULT();
    CALL BL_CL.SP_DM_LOAD_DIM_PAYMENT_DETAILS_DEFAULT();
    CALL BL_CL.SP_DM_LOAD_DIM_DEVICES_DEFAULT();
    
    CALL BL_CL.SP_3NF_LOAD_CE_CUSTOMERS();
    CALL BL_CL.SP_3NF_LOAD_CE_PRODUCT_CATEGORIES();
    CALL BL_CL.SP_3NF_LOAD_CE_PRODUCT_SUBCATEGORIES();
    CALL BL_CL.SP_3NF_LOAD_CE_PRODUCTS();
    CALL BL_CL.SP_3NF_LOAD_CE_REGIONS();
    CALL BL_CL.SP_3NF_LOAD_CE_COUNTRIES();
    CALL BL_CL.SP_3NF_LOAD_CE_CITIES();
    CALL BL_CL.SP_3NF_LOAD_CE_ADDRESSES();
    CALL BL_CL.SP_3NF_LOAD_CE_EMPLOYEES_SCD();
    CALL BL_CL.SP_3NF_LOAD_CE_PAYMENT_METHODS();
    CALL BL_CL.SP_3NF_LOAD_CE_CARD_TYPES();
    CALL BL_CL.SP_3NF_LOAD_CE_PAYMENT_DETAILS();
    CALL BL_CL.SP_3NF_LOAD_CE_DEVICES();
    CALL BL_CL.SP_3NF_LOAD_CE_SALES();
    
    CALL BL_CL.SP_DM_LOAD_DIM_CUSTOMERS();
    CALL BL_CL.SP_DM_LOAD_DIM_PRODUCTS();
    CALL BL_CL.SP_DM_LOAD_DIM_LOCATIONS();
    CALL BL_CL.SP_DM_LOAD_DIM_EMPLOYEES_SCD();
    CALL BL_CL.SP_DM_LOAD_DIM_PAYMENT_DETAILS();
    CALL BL_CL.SP_DM_LOAD_DIM_DEVICES();
    CALL BL_CL.SP_DM_LOAD_DIM_DATES();
    CALL BL_CL.SP_DM_LOAD_DIM_TIMES();
    CALL BL_CL.SP_DM_LOAD_FCT_SALES();
EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION 'ERROR EXECUTING MASTER PROCEDURE (%): %',  UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;
COMMIT;