BEGIN;
CREATE SCHEMA IF NOT EXISTS SA_OFFLINE;

CREATE EXTENSION IF NOT EXISTS FILE_FDW SCHEMA SA_OFFLINE;
CREATE SERVER IF NOT EXISTS FDW_SERVER FOREIGN DATA WRAPPER FILE_FDW;

DROP FOREIGN TABLE IF EXISTS SA_OFFLINE.EXT_OFFLINE_RETAIL_SALES;
CREATE FOREIGN TABLE IF NOT EXISTS SA_OFFLINE.EXT_OFFLINE_RETAIL_SALES 
(
    TRANSACTION_ID          VARCHAR(1000),
    TIMESTAMP               VARCHAR(1000),
    PRODUCT_ID              VARCHAR(1000),
    PRODUCT_NAME            VARCHAR(1000),
    PRICE                   VARCHAR(1000),
    PRODUCT_MANUFACTURER    VARCHAR(1000),
    PRODUCT_CATEGORY        VARCHAR(1000),
    PRODUCT_SUBCATEGORY     VARCHAR(1000),
    PURCHASE_REGION         VARCHAR(1000),
    PURCHASE_COUNTRY        VARCHAR(1000),
    PURCHASE_CITY           VARCHAR(1000),
    PURCHASE_ADDRESS        VARCHAR(1000),
    EMPLOYEE_ID             VARCHAR(1000),
    EMPLOYEE_FIRST_NAME     VARCHAR(1000),
    EMPLOYEE_LAST_NAME      VARCHAR(1000),
    EMPLOYEE_EMAIL          VARCHAR(1000),
    QUANTITY                VARCHAR(1000),
    DISCOUNT                VARCHAR(1000),
    TOTAL_AMOUNT            VARCHAR(1000),
    PAYMENT_METHOD          VARCHAR(1000),
    CARD_TYPE               VARCHAR(1000),
    VERIFICATION_METHOD     VARCHAR(1000)
) 
SERVER FDW_SERVER OPTIONS (FILENAME '.\\datasets\\offline_retail_sales.csv', FORMAT 'csv', HEADER 'true');
COMMIT;