BEGIN;
CREATE SCHEMA IF NOT EXISTS BL_3NF;
CREATE SCHEMA IF NOT EXISTS BL_CL;

DROP TABLE IF EXISTS BL_3NF.CE_CUSTOMERS;
CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS 
(
    CUSTOMER_ID     BIGINT,
    CUSTOMER_SRC_ID VARCHAR(255)    NOT NULL,
    FIRST_NAME      VARCHAR(50)     NOT NULL,
    LAST_NAME       VARCHAR(50)     NOT NULL,
    EMAIL           VARCHAR(100)    NOT NULL,
    AGE             SMALLINT        NOT NULL,
    GENDER          VARCHAR(10)     NOT NULL,
    SOURCE_SYSTEM   VARCHAR(255)    NOT NULL,
    SOURCE_ENTITY   VARCHAR(255)    NOT NULL,
    INSERT_DT       TIMESTAMP       NOT NULL,
    UPDATE_DT       TIMESTAMP       NOT NULL,
    CONSTRAINT      PK_CE_CUSTOMERS_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT      UNQ_CE_CUSTOMERS_CUSTOMER_SRC_ID UNIQUE (CUSTOMER_SRC_ID)
);

DROP SEQUENCE IF EXISTS BL_3NF.SEQ_CUSTOMER_ID;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CUSTOMER_ID START WITH 1 INCREMENT BY 1;

DROP PROCEDURE IF EXISTS BL_CL.SP_3NF_LOAD_CE_CUSTOMERS_DEFAULT;
CREATE OR REPLACE PROCEDURE BL_CL.SP_3NF_LOAD_CE_CUSTOMERS_DEFAULT()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_AFFECTED BIGINT;
BEGIN
    INSERT INTO BL_3NF.CE_CUSTOMERS (CUSTOMER_ID, CUSTOMER_SRC_ID, FIRST_NAME, LAST_NAME, EMAIL, AGE, GENDER, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    VALUES      (-1,
                'N/A', 
                'N/A',
                'N/A',
                'N/A',
                -1,
                'N/A',
                'MANUAL',
                'MANUAL',
                '1900-01-01 00:00:00',
                '1900-01-01 00:00:00')
    ON CONFLICT (CUSTOMER_ID) DO NOTHING;
    
    GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_CUSTOMERS_DEFAULT', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', 1, V_AFFECTED, 0, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_CUSTOMERS_DEFAULT', 'BL_CL', 'ERROR LOADING CE_CUSTOMERS', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING CE_CUSTOMERS (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;

DROP FUNCTION IF EXISTS BL_CL.FN_3NF_TRANSFORM_CUSTOMERS;
CREATE OR REPLACE FUNCTION BL_CL.FN_3NF_TRANSFORM_CUSTOMERS()
RETURNS TABLE
(
    CUSTOMER_ID     VARCHAR(255),
    FIRST_NAME      VARCHAR(50),
    LAST_NAME       VARCHAR(50),
    EMAIL           VARCHAR(100),
    AGE             SMALLINT,
    GENDER          VARCHAR(10),
    SOURCE_SYSTEM   VARCHAR(255),
    SOURCE_ENTITY   VARCHAR(255)
)
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_LAST_LOAD_DT TIMESTAMP;
BEGIN
    SELECT  LAST_LOAD_DT
    INTO    V_LAST_LOAD_DT
    FROM    BL_CL.MTA_LOADS
    WHERE   PROCEDURE_NAME = 'SP_3NF_LOAD_CE_CUSTOMERS' AND PROCEDURE_SCHEMA = 'BL_CL';
    
    IF V_LAST_LOAD_DT IS NULL THEN
        V_LAST_LOAD_DT := '1900-01-01 00:00:00';
    END IF;

    RETURN QUERY
        WITH SRC_CUSTOMERS_RANKED AS 
        (
            SELECT  SRC.CUSTOMER_ID,
                    SRC.CUSTOMER_FIRST_NAME,
                    SRC.CUSTOMER_LAST_NAME,
                    SRC.CUSTOMER_EMAIL,
                    SRC.CUSTOMER_AGE,
                    SRC.CUSTOMER_GENDER,
                    ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(SRC.CUSTOMER_ID)) ORDER BY SRC.TIMESTAMP::TIMESTAMP DESC) AS EVENT_RANK
            FROM    SA_ONLINE.SRC_ONLINE_RETAIL_SALES AS SRC
            WHERE   SRC.CUSTOMER_ID IS NOT NULL AND
                    SRC.LOAD_DT > V_LAST_LOAD_DT
        )
        SELECT  UPPER(TRIM(SRC.CUSTOMER_ID))::VARCHAR,
                COALESCE(UPPER(TRIM(SRC.CUSTOMER_FIRST_NAME)), 'N/A')::VARCHAR,
                COALESCE(UPPER(TRIM(SRC.CUSTOMER_LAST_NAME)), 'N/A')::VARCHAR,
                COALESCE(UPPER(TRIM(SRC.CUSTOMER_EMAIL)), 'N/A')::VARCHAR,
                COALESCE(TRIM(SRC.CUSTOMER_AGE), '-1')::SMALLINT,
                COALESCE(UPPER(TRIM(SRC.CUSTOMER_GENDER)), 'N/A')::VARCHAR,
                'SA_ONLINE'::VARCHAR,
                'SRC_ONLINE_RETAIL_SALES'::VARCHAR
        FROM    SRC_CUSTOMERS_RANKED AS SRC
        WHERE   SRC.EVENT_RANK = 1;
END;
$$;

DROP PROCEDURE IF EXISTS BL_CL.SP_3NF_LOAD_CE_CUSTOMERS;
CREATE OR REPLACE PROCEDURE BL_CL.SP_3NF_LOAD_CE_CUSTOMERS()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_REC           RECORD;
    V_INSERTED_ROWS BIGINT := 0;
    V_UPDATED_ROWS  BIGINT := 0;
    V_TOTAL_ROWS    BIGINT := 0;
    V_AFFECTED      BIGINT := 0;
    V_EXISTS        BOOLEAN;
BEGIN
    FOR V_REC IN SELECT * FROM BL_CL.FN_3NF_TRANSFORM_CUSTOMERS() LOOP
        SELECT  EXISTS (SELECT 1 FROM BL_3NF.CE_CUSTOMERS WHERE CUSTOMER_SRC_ID = V_REC.CUSTOMER_ID)
        INTO    V_EXISTS;
        
        INSERT INTO BL_3NF.CE_CUSTOMERS AS TARGET (CUSTOMER_ID, CUSTOMER_SRC_ID, FIRST_NAME, LAST_NAME, EMAIL, AGE, GENDER, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
        VALUES      (NEXTVAL('BL_3NF.SEQ_CUSTOMER_ID'),
                    V_REC.CUSTOMER_ID,
                    V_REC.FIRST_NAME,
                    V_REC.LAST_NAME,
                    V_REC.EMAIL,
                    V_REC.AGE,
                    V_REC.GENDER,
                    V_REC.SOURCE_SYSTEM,
                    V_REC.SOURCE_ENTITY,
                    CURRENT_TIMESTAMP,
                    CURRENT_TIMESTAMP)
        ON CONFLICT (CUSTOMER_SRC_ID) DO UPDATE
        SET         FIRST_NAME = EXCLUDED.FIRST_NAME,
                    LAST_NAME = EXCLUDED.LAST_NAME,
                    EMAIL = EXCLUDED.EMAIL,
                    AGE = EXCLUDED.AGE,
                    GENDER = EXCLUDED.GENDER,
                    UPDATE_DT = CURRENT_TIMESTAMP
        WHERE       TARGET.FIRST_NAME != EXCLUDED.FIRST_NAME OR
                    TARGET.LAST_NAME != EXCLUDED.LAST_NAME OR
                    TARGET.EMAIL != EXCLUDED.EMAIL OR
                    TARGET.AGE != EXCLUDED.AGE OR
                    TARGET.GENDER != EXCLUDED.GENDER;

        GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
        IF V_EXISTS THEN
            V_UPDATED_ROWS := V_UPDATED_ROWS + V_AFFECTED;
        ELSE
            V_INSERTED_ROWS := V_INSERTED_ROWS + V_AFFECTED;
        END IF;
        V_TOTAL_ROWS := V_TOTAL_ROWS + 1;
    END LOOP;
    
    CALL BL_CL.SP_MTA_UPDATE_LOAD('SP_3NF_LOAD_CE_CUSTOMERS', 'BL_CL');
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_CUSTOMERS', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', V_TOTAL_ROWS, V_INSERTED_ROWS, V_UPDATED_ROWS, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_CUSTOMERS', 'BL_CL', 'ERROR LOADING CE_CUSTOMERS', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING CE_CUSTOMERS (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;
COMMIT;