BEGIN;
CREATE SCHEMA IF NOT EXISTS BL_3NF;
CREATE SCHEMA IF NOT EXISTS BL_CL;

DROP TABLE IF EXISTS BL_3NF.CE_PAYMENT_METHODS;
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS
(
    PAYMENT_METHOD_ID       BIGINT,
    PAYMENT_METHOD_SRC_ID   VARCHAR(255)    NOT NULL,
    PAYMENT_METHOD_NAME     VARCHAR(50)     NOT NULL,
    SOURCE_SYSTEM           VARCHAR(255)    NOT NULL,
    SOURCE_ENTITY           VARCHAR(255)    NOT NULL,
    INSERT_DT               TIMESTAMP       NOT NULL,
    UPDATE_DT               TIMESTAMP       NOT NULL,
    CONSTRAINT              PK_CE_PAYMENT_METHODS_PAYMENT_METHOD_ID PRIMARY KEY (PAYMENT_METHOD_ID),
    CONSTRAINT              UNQ_CE_PAYMENT_METHODS_PAYMENT_METHOD_SRC_ID UNIQUE (PAYMENT_METHOD_SRC_ID)
);

DROP SEQUENCE IF EXISTS BL_3NF.SEQ_PAYMENT_METHOD_ID;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PAYMENT_METHOD_ID START WITH 1 INCREMENT BY 1;

DROP PROCEDURE IF EXISTS BL_CL.SP_3NF_LOAD_CE_PAYMENT_METHODS_DEFAULT;
CREATE OR REPLACE PROCEDURE BL_CL.SP_3NF_LOAD_CE_PAYMENT_METHODS_DEFAULT()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_AFFECTED BIGINT;
BEGIN
    INSERT INTO BL_3NF.CE_PAYMENT_METHODS (PAYMENT_METHOD_ID, PAYMENT_METHOD_SRC_ID, PAYMENT_METHOD_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    VALUES      (-1,
                'N/A',
                'N/A',
                'MANUAL',
                'MANUAL',
                '1900-01-01 00:00:00',
                '1900-01-01 00:00:00')
    ON CONFLICT (PAYMENT_METHOD_ID) DO NOTHING;
    
    GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PAYMENT_METHODS_DEFAULT', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', 1, V_AFFECTED, 0, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PAYMENT_METHODS_DEFAULT', 'BL_CL', 'ERROR LOADING CE_PAYMENT_METHODS', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING CE_PAYMENT_METHODS (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;

DROP FUNCTION IF EXISTS BL_CL.FN_3NF_TRANSFORM_PAYMENT_METHODS;
CREATE OR REPLACE FUNCTION BL_CL.FN_3NF_TRANSFORM_PAYMENT_METHODS()
RETURNS TABLE
(
    PAYMENT_METHOD_ID   VARCHAR(255),
    PAYMENT_METHOD_NAME  VARCHAR(50),
    SOURCE_SYSTEM       VARCHAR(255),
    SOURCE_ENTITY       VARCHAR(255)
)
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_LAST_LOAD_DT TIMESTAMP;
BEGIN
    SELECT  LAST_LOAD_DT
    INTO    V_LAST_LOAD_DT
    FROM    BL_CL.MTA_LOADS
    WHERE   PROCEDURE_NAME = 'SP_3NF_LOAD_CE_PAYMENT_METHODS' AND PROCEDURE_SCHEMA = 'BL_CL';
    
    IF V_LAST_LOAD_DT IS NULL THEN
        V_LAST_LOAD_DT := '1900-01-01 00:00:00';
    END IF;

    RETURN QUERY
        WITH T_MAP_PAYMENT_METHODS_RANKED AS 
        (
            SELECT  T_MAP.*,
                    ROW_NUMBER() OVER (PARTITION BY T_MAP.PAYMENT_METHOD_ID ORDER BY T_MAP.LOAD_DT DESC) AS LOAD_RANK
            FROM    BL_CL.T_MAP_PAYMENT_METHODS AS T_MAP
            WHERE   T_MAP.LOAD_DT > V_LAST_LOAD_DT
        )
        SELECT      T_MAP.PAYMENT_METHOD_ID::VARCHAR,
                    T_MAP.PAYMENT_METHOD_NAME,
                    'BL_CL'::VARCHAR,
                    'T_MAP_PAYMENT_METHODS'::VARCHAR
        FROM        T_MAP_PAYMENT_METHODS_RANKED AS T_MAP
        WHERE       T_MAP.LOAD_RANK = 1;
END;
$$;

DROP PROCEDURE IF EXISTS BL_CL.SP_3NF_LOAD_CE_PAYMENT_METHODS;
CREATE OR REPLACE PROCEDURE BL_CL.SP_3NF_LOAD_CE_PAYMENT_METHODS()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_REC           RECORD;
    V_INSERTED_ROWS BIGINT := 0;
    V_UPDATED_ROWS  BIGINT := 0;
    V_TOTAL_ROWS    BIGINT := 0;
    V_AFFECTED      BIGINT := 0;
    V_EXISTS        BOOLEAN;
BEGIN
    FOR V_REC IN SELECT * FROM BL_CL.FN_3NF_TRANSFORM_PAYMENT_METHODS() LOOP
        SELECT  EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_METHODS WHERE PAYMENT_METHOD_SRC_ID = V_REC.PAYMENT_METHOD_ID)
        INTO    V_EXISTS;
        
        INSERT INTO BL_3NF.CE_PAYMENT_METHODS AS TARGET (PAYMENT_METHOD_ID, PAYMENT_METHOD_SRC_ID, PAYMENT_METHOD_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
        VALUES      (NEXTVAL('BL_3NF.SEQ_PAYMENT_METHOD_ID'),
                    V_REC.PAYMENT_METHOD_ID,
                    V_REC.PAYMENT_METHOD_NAME,
                    V_REC.SOURCE_SYSTEM,
                    V_REC.SOURCE_ENTITY,
                    CURRENT_TIMESTAMP,
                    CURRENT_TIMESTAMP)
        ON CONFLICT (PAYMENT_METHOD_SRC_ID) DO UPDATE
        SET         PAYMENT_METHOD_NAME = EXCLUDED.PAYMENT_METHOD_NAME,
                    UPDATE_DT = CURRENT_TIMESTAMP
        WHERE       TARGET.PAYMENT_METHOD_NAME != EXCLUDED.PAYMENT_METHOD_NAME;
        
        GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
        IF V_EXISTS THEN
            V_UPDATED_ROWS := V_UPDATED_ROWS + V_AFFECTED;
        ELSE
            V_INSERTED_ROWS := V_INSERTED_ROWS + V_AFFECTED;
        END IF;
        V_TOTAL_ROWS := V_TOTAL_ROWS + 1;
    END LOOP;
    
    CALL BL_CL.SP_MTA_UPDATE_LOAD('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES', 'BL_CL');
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', V_TOTAL_ROWS, V_INSERTED_ROWS, V_UPDATED_ROWS, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES', 'BL_CL', 'ERROR LOADING CE_PRODUCT_CATEGORIES', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING CE_PRODUCT_CATEGORIES (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;
COMMIT;