BEGIN;
CREATE SCHEMA IF NOT EXISTS BL_3NF;
CREATE SCHEMA IF NOT EXISTS BL_CL;

DROP TABLE IF EXISTS BL_3NF.CE_PRODUCT_CATEGORIES;
CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCT_CATEGORIES
(
    PRODUCT_CATEGORY_ID     BIGINT,
    PRODUCT_CATEGORY_SRC_ID VARCHAR(255)    NOT NULL,
    CATEGORY_NAME           VARCHAR(50)     NOT NULL,
    SOURCE_SYSTEM           VARCHAR(255)    NOT NULL,
    SOURCE_ENTITY           VARCHAR(255)    NOT NULL,
    INSERT_DT               TIMESTAMP       NOT NULL,
    UPDATE_DT               TIMESTAMP       NOT NULL,
    CONSTRAINT              PK_CE_PRODUCT_CATEGORIES_PRODUCT_CATEGORY_ID PRIMARY KEY (PRODUCT_CATEGORY_ID),
    CONSTRAINT              UNQ_CE_PRODUCT_CATEGORIES_PRODUCT_CATEGORY_SRC_ID UNIQUE (PRODUCT_CATEGORY_SRC_ID)
);

DROP SEQUENCE IF EXISTS BL_3NF.SEQ_PRODUCT_CATEGORY_ID;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_PRODUCT_CATEGORY_ID START WITH 1 INCREMENT BY 1;

DROP PROCEDURE IF EXISTS BL_CL.SP_3NF_LOAD_CE_PRODUCT_CATEGORIES_DEFAULT;
CREATE OR REPLACE PROCEDURE BL_CL.SP_3NF_LOAD_CE_PRODUCT_CATEGORIES_DEFAULT()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_AFFECTED BIGINT;
BEGIN
    INSERT INTO BL_3NF.CE_PRODUCT_CATEGORIES (PRODUCT_CATEGORY_ID, PRODUCT_CATEGORY_SRC_ID, CATEGORY_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    VALUES      (-1,
                'N/A', 
                'N/A',
                'MANUAL',
                'MANUAL',
                '1900-01-01 00:00:00',
                '1900-01-01 00:00:00')
    ON CONFLICT (PRODUCT_CATEGORY_ID) DO NOTHING;
    
    GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES_DEFAULT', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', 1, V_AFFECTED, 0, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES_DEFAULT', 'BL_CL', 'ERROR LOADING CE_PRODUCT_CATEGORIES', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING CE_PRODUCT_CATEGORIES (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;

DROP FUNCTION IF EXISTS BL_CL.FN_3NF_TRANSFORM_PRODUCT_CATEGORIES;
CREATE OR REPLACE FUNCTION BL_CL.FN_3NF_TRANSFORM_PRODUCT_CATEGORIES()
RETURNS TABLE
(
    PRODUCT_CATEGORY_ID VARCHAR(255),
    CATEGORY_NAME       VARCHAR(50),
    SOURCE_SYSTEM       VARCHAR(255),
    SOURCE_ENTITY       VARCHAR(255)
)
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_LAST_LOAD_DT TIMESTAMP;
BEGIN
    SELECT  LAST_LOAD_DT
    INTO    V_LAST_LOAD_DT
    FROM    BL_CL.MTA_LOADS
    WHERE   PROCEDURE_NAME = 'SP_3NF_LOAD_CE_PRODUCT_CATEGORIES' AND PROCEDURE_SCHEMA = 'BL_CL';
    
    IF V_LAST_LOAD_DT IS NULL THEN
        V_LAST_LOAD_DT := '1900-01-01 00:00:00';
    END IF;

    RETURN QUERY
        WITH T_MAP_PRODUCT_CATEGORIES_RANKED AS 
        (
            SELECT  T_MAP.*,
                    ROW_NUMBER() OVER (PARTITION BY T_MAP.PRODUCT_CATEGORY_ID ORDER BY T_MAP.LOAD_DT DESC) AS LOAD_RANK
            FROM    BL_CL.T_MAP_PRODUCT_CATEGORIES AS T_MAP
            WHERE   T_MAP.LOAD_DT > V_LAST_LOAD_DT
        )
        SELECT  T_MAP.PRODUCT_CATEGORY_ID::VARCHAR,
                T_MAP.CATEGORY_NAME,
                'BL_CL'::VARCHAR,
                'T_MAP_PRODUCT_CATEGORIES'::VARCHAR
        FROM    T_MAP_PRODUCT_CATEGORIES_RANKED AS T_MAP
        WHERE   T_MAP.LOAD_RANK = 1;
END;
$$;

DROP PROCEDURE IF EXISTS BL_CL.SP_3NF_LOAD_CE_PRODUCT_CATEGORIES;
CREATE OR REPLACE PROCEDURE BL_CL.SP_3NF_LOAD_CE_PRODUCT_CATEGORIES()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_REC           RECORD;
    V_INSERTED_ROWS BIGINT := 0;
    V_UPDATED_ROWS  BIGINT := 0;
    V_TOTAL_ROWS    BIGINT := 0;
    V_AFFECTED      BIGINT := 0;
    V_EXISTS        BOOLEAN;
BEGIN
    FOR V_REC IN SELECT * FROM BL_CL.FN_3NF_TRANSFORM_PRODUCT_CATEGORIES() LOOP
        SELECT  EXISTS (SELECT 1 FROM BL_3NF.CE_PRODUCT_CATEGORIES WHERE PRODUCT_CATEGORY_SRC_ID = V_REC.PRODUCT_CATEGORY_ID)
        INTO    V_EXISTS;
        
        INSERT INTO BL_3NF.CE_PRODUCT_CATEGORIES AS TARGET (PRODUCT_CATEGORY_ID, PRODUCT_CATEGORY_SRC_ID, CATEGORY_NAME, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
        VALUES      (NEXTVAL('BL_3NF.SEQ_PRODUCT_CATEGORY_ID'),
                    V_REC.PRODUCT_CATEGORY_ID,
                    V_REC.CATEGORY_NAME,
                    V_REC.SOURCE_SYSTEM,
                    V_REC.SOURCE_ENTITY,
                    CURRENT_TIMESTAMP,
                    CURRENT_TIMESTAMP)
        ON CONFLICT (PRODUCT_CATEGORY_SRC_ID) DO UPDATE
        SET         CATEGORY_NAME = EXCLUDED.CATEGORY_NAME,
                    UPDATE_DT = CURRENT_TIMESTAMP
        WHERE       TARGET.CATEGORY_NAME != EXCLUDED.CATEGORY_NAME;
        
        GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
        IF V_EXISTS THEN
            V_UPDATED_ROWS := V_UPDATED_ROWS + V_AFFECTED;
        ELSE
            V_INSERTED_ROWS := V_INSERTED_ROWS + V_AFFECTED;
        END IF;
        V_TOTAL_ROWS := V_TOTAL_ROWS + 1;
    END LOOP;
    
    CALL BL_CL.SP_MTA_UPDATE_LOAD('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES', 'BL_CL');
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', V_TOTAL_ROWS, V_INSERTED_ROWS, V_UPDATED_ROWS, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_3NF_LOAD_CE_PRODUCT_CATEGORIES', 'BL_CL', 'ERROR LOADING CE_PRODUCT_CATEGORIES', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING CE_PRODUCT_CATEGORIES (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;
COMMIT;