BEGIN;
CREATE SCHEMA IF NOT EXISTS SA_ONLINE;

CREATE EXTENSION IF NOT EXISTS FILE_FDW SCHEMA SA_ONLINE;
CREATE SERVER IF NOT EXISTS FDW_SERVER FOREIGN DATA WRAPPER FILE_FDW;

DROP FOREIGN TABLE IF EXISTS SA_ONLINE.EXT_ONLINE_RETAIL_SALES;
CREATE FOREIGN TABLE IF NOT EXISTS SA_ONLINE.EXT_ONLINE_RETAIL_SALES
(
    TRANSACTION_ID          VARCHAR(1000),
    TIMESTAMP               VARCHAR(1000),
    CUSTOMER_ID             VARCHAR(1000),
    CUSTOMER_FIRST_NAME     VARCHAR(1000),
    CUSTOMER_LAST_NAME      VARCHAR(1000),
    CUSTOMER_EMAIL          VARCHAR(1000),
    CUSTOMER_AGE            VARCHAR(1000),
    CUSTOMER_GENDER         VARCHAR(1000),
    PRODUCT_ID              VARCHAR(1000),
    PRODUCT_NAME            VARCHAR(1000),
    PRICE                   VARCHAR(1000),
    PRODUCT_MANUFACTURER    VARCHAR(1000),
    PRODUCT_CATEGORY        VARCHAR(1000),
    PRODUCT_SUBCATEGORY     VARCHAR(1000),
    QUANTITY                VARCHAR(1000),
    DISCOUNT                VARCHAR(1000),
    TOTAL_AMOUNT            VARCHAR(1000),
    PAYMENT_METHOD          VARCHAR(1000),
    CARD_TYPE               VARCHAR(1000),
    VERIFICATION_METHOD     VARCHAR(1000),
    DEVICE_TYPE             VARCHAR(1000),
    BROWSER_USED            VARCHAR(1000)
)
SERVER FDW_SERVER OPTIONS (FILENAME '.\\datasets\\online_retail_sales.csv', FORMAT 'csv', HEADER 'true');
COMMIT;