BEGIN;
CREATE SCHEMA IF NOT EXISTS BL_DM;
CREATE SCHEMA IF NOT EXISTS BL_CL;

DROP TABLE IF EXISTS BL_DM.DIM_DEVICES;
CREATE TABLE IF NOT EXISTS BL_DM.DIM_DEVICES
(
    DEVICE_SURR_ID  BIGINT,
    DEVICE_SRC_ID   VARCHAR(255)    NOT NULL,
    DEVICE_TYPE     VARCHAR(50)     NOT NULL,
    BROWSER_USED    VARCHAR(50)     NOT NULL,
    SOURCE_SYSTEM   VARCHAR(255)    NOT NULL,
    SOURCE_ENTITY   VARCHAR(255)    NOT NULL,
    INSERT_DT       TIMESTAMP       NOT NULL,
    UPDATE_DT       TIMESTAMP       NOT NULL,
    CONSTRAINT      PK_DIM_DEVICES_DEVICE_SURR_ID PRIMARY KEY (DEVICE_SURR_ID),
    CONSTRAINT      UNQ_DIM_DEVICES_DEVICE_SRC_ID UNIQUE (DEVICE_SRC_ID)
);

DROP SEQUENCE IF EXISTS BL_DM.SEQ_DEVICE_SURR_ID;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DEVICE_SURR_ID START WITH 1 INCREMENT BY 1;

DROP PROCEDURE IF EXISTS BL_CL.SP_DM_LOAD_DIM_DEVICES_DEFAULT;
CREATE OR REPLACE PROCEDURE BL_CL.SP_DM_LOAD_DIM_DEVICES_DEFAULT()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_AFFECTED BIGINT;
BEGIN
    INSERT INTO BL_DM.DIM_DEVICES (DEVICE_SURR_ID, DEVICE_SRC_ID, DEVICE_TYPE, BROWSER_USED, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
    VALUES      (-1,
                'N/A',
                'N/A',
                'N/A',
                'MANUAL',
                'MANUAL',
                '1900-01-01 00:00:00',
                '1900-01-01 00:00:00')
    ON CONFLICT (DEVICE_SURR_ID) DO NOTHING;
    
    GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_DM_LOAD_DIM_DEVICES_DEFAULT', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', 1, V_AFFECTED, 0, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_DM_LOAD_DIM_DEVICES_DEFAULT', 'BL_CL', 'ERROR LOADING DIM_DEVICES', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING DIM_DEVICES (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;

DROP TYPE IF EXISTS BL_DM.DEVICE_TYPE CASCADE;
CREATE TYPE BL_DM.DEVICE_TYPE AS
(
    DEVICE_ID       VARCHAR(255),
    DEVICE_TYPE     VARCHAR(50),
    BROWSER_USED    VARCHAR(50),
    SOURCE_SYSTEM   VARCHAR(255),
    SOURCE_ENTITY   VARCHAR(255)
);

DROP FUNCTION IF EXISTS BL_CL.FN_DM_TRANSFORM_DEVICES;
CREATE OR REPLACE FUNCTION BL_CL.FN_DM_TRANSFORM_DEVICES()
RETURNS SETOF BL_DM.DEVICE_TYPE
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_LAST_LOAD_DT TIMESTAMP;
BEGIN
    SELECT  LAST_LOAD_DT
    INTO    V_LAST_LOAD_DT
    FROM    BL_CL.MTA_LOADS
    WHERE   PROCEDURE_NAME = 'SP_DM_LOAD_DIM_DEVICES' AND PROCEDURE_SCHEMA = 'BL_CL';
    
    IF V_LAST_LOAD_DT IS NULL THEN
        V_LAST_LOAD_DT := '1900-01-01 00:00:00';
    END IF;    

    RETURN QUERY
        SELECT  CE.DEVICE_ID::VARCHAR(255),
                CE.DEVICE_TYPE,
                CE.BROWSER_USED,
                'BL_3NF'::VARCHAR(255),
                'CE_DEVICES'::VARCHAR(255)
        FROM    BL_3NF.CE_DEVICES AS CE
        WHERE   CE.DEVICE_ID > 0 AND
                CE.UPDATE_DT > V_LAST_LOAD_DT;
END;
$$;

DROP PROCEDURE IF EXISTS BL_CL.SP_DM_LOAD_DIM_DEVICES;
CREATE OR REPLACE PROCEDURE BL_CL.SP_DM_LOAD_DIM_DEVICES()
LANGUAGE PLPGSQL
AS $$
DECLARE
    V_DEVICE        BL_DM.DEVICE_TYPE;
    V_CURSOR        REFCURSOR;
    V_INSERTED_ROWS BIGINT := 0;
    V_UPDATED_ROWS  BIGINT := 0;
    V_TOTAL_ROWS    BIGINT := 0;
    V_AFFECTED      BIGINT := 0;
    V_EXISTS        BOOLEAN;
BEGIN
    OPEN V_CURSOR FOR SELECT * FROM BL_CL.FN_DM_TRANSFORM_DEVICES();

    LOOP
        FETCH V_CURSOR INTO V_DEVICE;
        EXIT WHEN NOT FOUND;
    
        SELECT  EXISTS (SELECT 1 FROM BL_DM.DIM_DEVICES WHERE DEVICE_SRC_ID = V_DEVICE.DEVICE_ID)
        INTO    V_EXISTS;
        
        INSERT INTO BL_DM.DIM_DEVICES AS TARGET (DEVICE_SURR_ID, DEVICE_SRC_ID, DEVICE_TYPE, BROWSER_USED, SOURCE_SYSTEM, SOURCE_ENTITY, INSERT_DT, UPDATE_DT)
        VALUES      (NEXTVAL('BL_DM.SEQ_DEVICE_SURR_ID'),
                    V_DEVICE.DEVICE_ID,
                    V_DEVICE.DEVICE_TYPE,
                    V_DEVICE.BROWSER_USED,
                    V_DEVICE.SOURCE_SYSTEM,
                    V_DEVICE.SOURCE_ENTITY,
                    CURRENT_TIMESTAMP,
                    CURRENT_TIMESTAMP)
        ON CONFLICT (DEVICE_SRC_ID) DO UPDATE
        SET         DEVICE_TYPE = EXCLUDED.DEVICE_TYPE,
                    BROWSER_USED = EXCLUDED.BROWSER_USED,
                    UPDATE_DT = CURRENT_TIMESTAMP
        WHERE       TARGET.DEVICE_TYPE != EXCLUDED.DEVICE_TYPE OR
                    TARGET.BROWSER_USED != EXCLUDED.BROWSER_USED;

        GET DIAGNOSTICS V_AFFECTED = ROW_COUNT;
        IF V_EXISTS THEN
            V_UPDATED_ROWS := V_UPDATED_ROWS + V_AFFECTED;
        ELSE
            V_INSERTED_ROWS := V_INSERTED_ROWS + V_AFFECTED;
        END IF;
        V_TOTAL_ROWS := V_TOTAL_ROWS + 1;
    END LOOP;
    
    CLOSE V_CURSOR;
    CALL BL_CL.SP_MTA_UPDATE_LOAD('SP_DM_LOAD_DIM_DEVICES', 'BL_CL');
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_DM_LOAD_DIM_DEVICES', 'BL_CL', 'LOAD PERFORMED SUCCESSFULLY', V_TOTAL_ROWS, V_INSERTED_ROWS, V_UPDATED_ROWS, 'N/A', 'N/A');
EXCEPTION WHEN OTHERS THEN
    BEGIN
        CLOSE V_CURSOR;
    EXCEPTION WHEN OTHERS THEN END;
    
    CALL BL_CL.SP_MTA_INSERT_LOG('SP_DM_LOAD_DIM_DEVICES', 'BL_CL', 'ERROR LOADING DIM_DEVICES', -1, -1, -1, UPPER(SQLSTATE), UPPER(SQLERRM));
    COMMIT;
    RAISE EXCEPTION 'ERROR LOADING DIM_DEVICES (%): %', UPPER(SQLSTATE), UPPER(SQLERRM);
END;
$$;
COMMIT;